// RootLayout.tsx
"use client";
import React from "react";
import Provider from "./provider";
import Top from "../components/Top";
import Footer from "../components/Footer";
import { Provider as ReduxProvider } from "react-redux";
import { store } from "../store";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider store={store}>
          <Provider>
            <Top />
            {children}
            <Footer />
          </Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
