# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "runnigngngngngn"
      
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']
    
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure Docker daemon
        run: |
          echo '{ "insecure-registries": ["180.150.207.73:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 180.150.207.73:5000

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            180.150.207.73:5000/backend:${{ github.sha }}
            180.150.207.73:5000/backend:latest
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
            
            
            
            
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags has to be all lower-case
          tags: |
            imrishav/gitops01:${{ github.sha }} 
            ghcr.io/imrishav/gitops01:${{ github.sha }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
#   update-manifest-stage:
#     runs-on: ubuntu-latest
#     needs: ['build-and-push-docker-image']
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           repository: mastgm0817/frontend
#           ref: 'main'
#           token: ${{ secrets.G_TOKEN }}
#       - name: setup git config
#         run: |
#           git config --global user.email "mastgm0817@gmail.com"
#           git config --global user.name "mastgm0817"
#           echo ${{ github.sha }}
#           sed -i "s#${{ github.actor }}.*#${{ github.actor }}/gitops01:${{ github.sha }}#g" deploy/deployment.yaml
#           git add -A
#           git commit -am "Update image for - ${{ github.sha }}"
#       - run: echo ${{ github }}
#       - run: git push origin master
